name: remote_monitor_app_movil
description: "Aplicación para monitoreo remoto de dispositivos móviles"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Base de datos local
  sqflite: ^2.4.2
  path_provider: ^2.1.1

  # Sensores y estado del dispositivo
  geolocator: ^14.0.2
  permission_handler: ^11.3.0
  network_info_plus: ^6.1.4
  device_info_plus: ^11.5.0
  battery_plus: ^6.2.2
  connectivity_plus: ^6.1.4
  provider : ^6.1.5
  # Servidor HTTP
  shelf: ^1.4.2
  shelf_router: ^1.1.4
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true